/**
 * Startup and wiring. Holds the one state object, chooses the text on
 * screen, and runs the one path to paper:
 * requestRender → buildWorksheet → measureWorksheet → renderWorksheet.
 * Each panel is a ui/* module that writes its own slice of state and asks
 * for a render; none of them builds a sheet itself.
 */

// Both generated by scripts/build.mjs: every registered language's pack and
// locale (src/languages.js), and every bundled picture.
import languageData from './generated/languageData.json';
import imageData from './generated/imageData.json';

import { LANGUAGE_CODES, DEFAULT_LANGUAGE, languageName } from './languages.js';
import { createLibrary } from './content/library.js';
import { findCandidates, chooseEntry, listThemes } from './content/catalog.js';
import { validateSettings } from './worksheet/validateSettings.js';
import { DEFAULT_SETTINGS, PAGE_WIDTH_MM, PREVIEW_SIDE_GAP_PX, mmToPx } from './config.js';
import { buildWorksheet } from './worksheet/build.js';
import { renderWorksheet } from './render/html.js';
import { measureWorksheet } from './layout/measure.js';
import { isPrintReady } from './export/print.js';
import { createTranslator, sheetLabels } from './i18n.js';
import { checkStorageCapability, listOwnTexts } from './storage.js';
import { emptySelection, keyFor } from './worksheet/selection.js';
import { tokenize } from './text/tokenize.js';
import { findElements } from './ui/elements.js';
import { init as initFitStatus } from './ui/fitStatus.js';
import { init as initActivityPanel } from './ui/activityPanel.js';
import { init as initImagePanel } from './ui/imagePanel.js';
import { init as initOwnTextPanel } from './ui/ownTextPanel.js';
import { init as initOutputButtons } from './ui/outputButtons.js';
import { init as initPacketUi } from './ui/packet.js';
import { init as initPresetsUi } from './ui/presets.js';
import { init as initContentImportUi } from './ui/contentImport.js';
import { init as initSettingsPanelUi } from './ui/settingsPanel.js';

const LOCALES = Object.fromEntries(LANGUAGE_CODES.map((code) => [code, languageData[code].locale]));

/** @type {Map<string, import('./worksheet/build.js').ImageAsset>} */
const IMAGES_BY_ID = new Map(
  Object.entries(imageData).map(([id, { dataUrl, width, height }]) => [id, { id, path: dataUrl, width, height }])
);

const library = createLibrary({
  packs: Object.fromEntries(LANGUAGE_CODES.map((code) => [code, languageData[code].pack])),
  assetIds: new Set(IMAGES_BY_ID.keys()),
  ownTexts: listOwnTexts()
});

/**
 * The single mutable state object.
 * @typedef {object} AppState
 * @property {string} language
 * @property {{ theme: string, level: number }} filter the theme and level chosen in the menus
 * @property {string | null} contentId the text on screen
 * @property {number} revision bumped by every render; a slower, older render is discarded
 * @property {import('./worksheet/build.js').WorksheetSettings} settings saved in setups, copied into every model
 * @property {{ grayscale: boolean }} view how the preview is viewed; never printed or saved
 * @property {import('./worksheet/selection.js').Selection | null} selection the clicks on the text on screen; never saved
 * @property {import('./worksheet/build.js').ImageAsset | null} customImage for this session only
 * @property {{ model: import('./worksheet/build.js').WorksheetModel, layout: import('./layout/measure.js').PageLayout, pageCount: number } | null} lastGood the printable sheet on screen
 * @property {import('./worksheet/packet.js').PacketSnapshot[]} packet frozen copies, never live references
 */

/** @type {AppState} */
const state = {
  language: DEFAULT_LANGUAGE,
  filter: { theme: listThemes(library.catalog(DEFAULT_LANGUAGE))[0], level: 1 },
  contentId: null,
  revision: 0,
  // A copy: the settings panel changes it in place.
  settings: /** @type {import('./worksheet/build.js').WorksheetSettings} */ (structuredClone(DEFAULT_SETTINGS)),
  view: { grayscale: false },
  selection: null,
  customImage: null,
  lastGood: null,
  packet: []
};

const settingsCheck = validateSettings(state.settings);
if (!settingsCheck.ok) {
  // eslint-disable-next-line no-console
  console.error('Default settings failed validation:', settingsCheck.errors);
  throw new Error('Default settings failed validation — see console for details.');
}

// Replaced on a language switch; the panels get it through getT.
let t = createTranslator(LOCALES[DEFAULT_LANGUAGE]);
const getT = () => t;
const els = findElements();

/** The texts of the language on screen. */
const catalog = () => library.catalog(state.language);

/** The text on screen, if any. */
function shownEntry() {
  return state.contentId ? catalog().byId.get(state.contentId) : undefined;
}

/** The text on screen, tokenized; null before one is shown. */
function shownDoc() {
  const entry = shownEntry();
  return entry ? tokenize({ body: entry.body, syllable_body: entry.syllable_body }) : null;
}

const fitStatus = initFitStatus({ state, els, getT });
const activityPanel = initActivityPanel({ state, els, getT, getDoc: shownDoc, requestRender });
const imagePanel = initImagePanel({ state, els, getT, requestRender });
const ownTextPanel = initOwnTextPanel({ state, els, getT, library, shownEntry, showText: showTextById, showFirstOfCell, textsChanged: updateCandidateCount });
initOutputButtons({ state, els, getT, whenRendered, showProblem: (text) => fitStatus.showMessage(text, { problem: true }) });
const { renderPacketList, updatePacketControls } = initPacketUi({ state, els, getT, whenRendered });
const { populateFontSelect, applySettingsLimits, syncSettingsControlsFromState } = initSettingsPanelUi({ state, els, requestRender, getT });
const { populatePresetSelect } = initPresetsUi({
  state,
  els,
  getT,
  switchLanguage,
  syncSettingsControlsFromState,
  updateCandidateCount,
  createText,
  requestRender,
  forgetOwnTexts
});
initContentImportUi({ state, els, getT, imagesById: IMAGES_BY_ID, replaceTexts, updateCandidateCount, showNoText });

/** The side controls that follow the text and the mode; after every render and mode change. */
function syncSideControls() {
  activityPanel.sync();
  ownTextPanel.sync();
}

/** Applies t() to every element carrying a data-label (text), data-placeholder or data-aria-label key. */
function applyStaticLabels() {
  document.documentElement.lang = state.language;
  document.title = t('app.title');
  for (const el of /** @type {NodeListOf<HTMLElement>} */ (document.querySelectorAll('[data-label]'))) {
    el.textContent = t(String(el.dataset.label));
  }
  for (const el of /** @type {NodeListOf<HTMLInputElement>} */ (document.querySelectorAll('[data-placeholder]'))) {
    el.placeholder = t(String(el.dataset.placeholder));
  }
  for (const el of /** @type {NodeListOf<HTMLElement>} */ (document.querySelectorAll('[data-aria-label]'))) {
    el.setAttribute('aria-label', t(String(el.dataset.ariaLabel)));
  }
}

/**
 * @param {HTMLSelectElement} select
 * @param {Array<[string, string]>} options [value, label]
 * @param {string} value
 */
function fillSelect(select, options, value) {
  select.replaceChildren(
    ...options.map(([optionValue, label]) => {
      const option = document.createElement('option');
      option.value = optionValue;
      option.textContent = label;
      return option;
    })
  );
  select.value = value;
}

function populateThemeSelect() {
  fillSelect(els.themeSelect, listThemes(catalog()).map((theme) => [theme, t(`theme.${theme}`)]), state.filter.theme);
}

/** Each language by its own name, whatever the interface language. */
function populateLanguageSelect() {
  fillSelect(els.languageSelect, LANGUAGE_CODES.map((code) => [code, languageName(code)]), state.language);
}

/**
 * The interface and the texts in another language. Theme and level stay
 * (their ids are the same in every language); the caller decides whether
 * to show a text.
 * @param {string} language
 */
function switchLanguage(language) {
  state.language = language;
  t = createTranslator(LOCALES[language]);
  applyStaticLabels();
  populateLanguageSelect();
  populateThemeSelect();
  populatePresetSelect(); // the built-in setups' names are translated
  renderPacketList();
}

/**
 * A content pack imported for this session replaces a language's texts.
 * @param {string} language
 * @param {import('./content/catalog.js').CatalogEntry[]} entries
 */
function replaceTexts(language, entries) {
  library.replaceTexts(language, entries);
  if (language === state.language) populateThemeSelect();
}

/** "Reset saved data" removed the own texts from storage: from this session too. */
function forgetOwnTexts() {
  library.setOwnTexts([]);
  updateCandidateCount();
  if (state.contentId && !shownEntry()) showFirstOfCell();
}

/**
 * The number of texts for the chosen theme and level, and their titles. It
 * never changes the sheet on screen: a new theme or level shows a text only
 * on "Create text" or a chosen title.
 */
function updateCandidateCount() {
  const candidates = findCandidates(catalog(), state.filter);
  els.candidateCount.textContent = candidates.length > 0
    ? t('candidates.available', { count: candidates.length })
    : t('candidates.none');
  els.createButton.disabled = candidates.length === 0;
  populateTextSelect(candidates);
}

/**
 * The title picker, shown when there is more than one text to choose from.
 * @param {import('./content/catalog.js').CatalogEntry[]} candidates
 */
function populateTextSelect(candidates) {
  const show = candidates.length > 1;
  els.textSelect.hidden = !show;
  els.textSelectLabel.hidden = !show;
  if (!show) {
    els.textSelect.replaceChildren();
    return;
  }
  fillSelect(els.textSelect, candidates.map((entry) => [entry.id, entry.title]), '');
  syncTextSelect(candidates);
}

/**
 * Marks the text on screen in the picker; nothing is marked while the menus
 * show another cell than the text on screen.
 * @param {import('./content/catalog.js').CatalogEntry[]} [candidates]
 */
function syncTextSelect(candidates = findCandidates(catalog(), state.filter)) {
  if (els.textSelect.hidden) return;
  const shown = candidates.some((c) => c.id === state.contentId);
  els.textSelect.value = shown ? state.contentId ?? '' : '';
  if (!shown) els.textSelect.selectedIndex = -1;
}

/** @param {import('./content/catalog.js').CatalogEntry} entry */
function showEntry(entry) {
  state.contentId = entry.id;
  state.selection = emptySelection(keyFor(entry));
  imagePanel.reset(); // a new text comes with its own picture
  syncTextSelect();
  requestRender();
}

/** @param {string} id */
function showTextById(id) {
  const entry = catalog().byId.get(id);
  if (entry) showEntry(entry);
}

/** "Create text": the next text of the chosen cell, in pack order. */
function createText() {
  const entry = chooseEntry(findCandidates(catalog(), state.filter), state.contentId);
  if (entry) showEntry(entry);
}

/** After the text on screen was removed: the cell's first text, or nothing printable. */
function showFirstOfCell() {
  state.contentId = null;
  const next = chooseEntry(findCandidates(catalog(), state.filter), null);
  if (next) showEntry(next);
  else clearPrintableWorksheet();
}

/** @param {string} mode */
function updateWritingMode(mode) {
  state.settings.writingMode = /** @type {import('./worksheet/build.js').WorksheetSettings['writingMode']} */ (mode);
  // Writing about the picture needs one: "None" is not offered meanwhile.
  if (mode === 'write-own' && state.settings.imageSlot === 'none') state.settings.imageSlot = 'picture';
  syncSettingsControlsFromState();
  syncSideControls();
  if (state.contentId) requestRender();
}

/** Nothing printable: no preview, no print surface, every output disabled. */
function clearPrintableWorksheet() {
  state.lastGood = null;
  els.printButton.disabled = true;
  els.docxButton.disabled = true;
  els.preview.replaceChildren();
  els.printSurface.replaceChildren();
  updatePacketControls();
}

/** No text on screen (a content import replaced the language's texts); a render in flight is discarded. */
function showNoText() {
  state.revision += 1;
  state.contentId = null;
  state.selection = null;
  clearPrintableWorksheet();
  fitStatus.showMessage(t('preview.empty'));
  syncSideControls();
}

/** The latest render: output waits for it (see whenRendered). */
let latestRender = Promise.resolve();

function requestRender() {
  latestRender = renderNow();
  return latestRender;
}

/** Resolves once no render is in flight (Print, Word and "Add to packet" wait for it). */
async function whenRendered() {
  let render;
  do {
    render = latestRender;
    await render;
  } while (render !== latestRender);
}

async function renderNow() {
  const revision = ++state.revision;
  try {
    const entry = shownEntry();
    if (!entry) throw new Error('NO_TEXT: there is no text on screen to render');
    // An uploaded picture replaces the text's own for this render only.
    /** @type {Map<string | null, import('./worksheet/build.js').ImageAsset>} */
    const imagesById = new Map(IMAGES_BY_ID);
    if (state.customImage) imagesById.set(entry.imageId, state.customImage);
    const model = buildWorksheet(entry, state.settings, { imagesById }, entry.language, state.selection);

    const labels = sheetLabels(t);
    const result = await measureWorksheet(model, revision, labels);
    if (revision !== state.revision) return; // a newer render has started

    fitStatus.showFit(model, result);
    els.printButton.disabled = !isPrintReady(result);
    els.docxButton.disabled = !isPrintReady(result);
    if (result.status === 'blocked') {
      clearPrintableWorksheet();
      syncSideControls(); // an own text that can't be laid out must stay deletable
      return;
    }

    // Page-break markers in the preview only (previewMode).
    renderWorksheet(model, result.layout, els.preview, labels, true);
    renderWorksheet(model, result.layout, els.printSurface, labels);
    state.lastGood = { model, layout: result.layout, pageCount: result.pageCount };
    updatePacketControls();
    syncSideControls();
  } catch (error) {
    // A sheet that failed to build must never stay printable.
    if (revision !== state.revision) return;
    // eslint-disable-next-line no-console
    console.error('Worksheet could not be prepared:', error);
    clearPrintableWorksheet();
    fitStatus.showMessage(t('fit.internalError', { message: error.message }), { problem: true });
  }
}

els.languageSelect.addEventListener('change', () => {
  switchLanguage(els.languageSelect.value);
  updateCandidateCount();
  imagePanel.reset();
  createText();
});
els.themeSelect.addEventListener('change', () => {
  state.filter.theme = els.themeSelect.value;
  updateCandidateCount();
});
els.levelSelect.addEventListener('change', () => {
  state.filter.level = Number(els.levelSelect.value);
  updateCandidateCount();
});
els.createButton.addEventListener('click', createText);
els.textSelect.addEventListener('change', () => {
  const entry = findCandidates(catalog(), state.filter).find((c) => c.id === els.textSelect.value);
  if (entry) showEntry(entry);
});
els.writingModeSelect.addEventListener('change', () => updateWritingMode(els.writingModeSelect.value));
els.copyTargetSelect.addEventListener('change', () => {
  state.settings.copyTarget = /** @type {import('./worksheet/build.js').WorksheetSettings['copyTarget']} */ (els.copyTargetSelect.value);
  syncSideControls();
  if (state.contentId) requestRender();
});
els.imageSlotSelect.addEventListener('change', () => {
  state.settings.imageSlot = /** @type {import('./worksheet/build.js').WorksheetSettings['imageSlot']} */ (els.imageSlotSelect.value);
  if (state.contentId) requestRender();
});

applyStaticLabels();
populateLanguageSelect();
populateThemeSelect();
populateFontSelect();
updateCandidateCount();
applySettingsLimits();
syncSettingsControlsFromState();
populatePresetSelect();
updatePacketControls();
renderPacketList();
if (!checkStorageCapability()) {
  els.storageStatus.textContent = t('preset.storageUnavailable');
  els.savePresetButton.disabled = true;
}
fitStatus.showMessage(t('fit.measuring'));

// The on-screen A4 page is scaled down to the available width (never up).
// Display only: the fit check measures in its own unscaled surface.
{
  const fitPreview = () => {
    const available = els.previewScroll.clientWidth - PREVIEW_SIDE_GAP_PX;
    const scale = Math.min(1, available / mmToPx(PAGE_WIDTH_MM));
    els.pageFrame.style.setProperty('--preview-scale', scale.toFixed(3));
  };
  if (typeof ResizeObserver !== 'undefined') new ResizeObserver(fitPreview).observe(els.previewScroll);
  fitPreview();
}

createText(); // show something on first load rather than an empty preview
